### ISSUE TITLE
How to use custom slave port?

### ISSUE THREAD

**Issue by rakesh-roshan** [jenkinsci/docker-jnlp-slave#18]
My jenkin server is using 40002 as slave port but the slave container tries to connect to 50000. How to pass this option?

**Comment by rakesh-roshan** [comment]
I tried using -tunnel option, it throws error,

rroshan@roshan-PC:~/coreos-ansible$ docker run --rm --name slave1 jenkinsci/jnlp-slave -url http://10.160.58.213:32401/ -tunnel 10.160.58.213:32501 1234 temp_slave
Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior
Nov 10, 2016 4:46:02 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: temp_slave
Nov 10, 2016 4:46:02 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Nov 10, 2016 4:46:02 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://10.160.58.213:32401/]
Nov 10, 2016 4:46:03 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Nov 10, 2016 4:46:03 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to 10.160.58.213:32501
Nov 10, 2016 4:46:03 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP3-connect is not enabled, skipping
Nov 10, 2016 4:46:03 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP2-connect
Nov 10, 2016 4:46:03 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server didn't accept the handshake: JNLP2-connect: rejected connection for node: temp_slave
Nov 10, 2016 4:46:03 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to 10.160.58.213:32501
Nov 10, 2016 4:46:03 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP-connect
Nov 10, 2016 4:46:04 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server didn't accept the handshake: Unauthorized access
Nov 10, 2016 4:46:04 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to 10.160.58.213:32501
Nov 10, 2016 4:46:04 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
        at hudson.remoting.Engine.onConnectionRejected(Engine.java:353)
        at hudson.remoting.Engine.run(Engine.java:325)

**Server**

Nov 10, 2016 4:46:03 PM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFO: Accepted connection #5 from /172.42.28.1:46118
Nov 10, 2016 4:46:03 PM org.jenkinsci.remoting.engine.JnlpServerHandshake error
WARNING: TCP agent connection handler #5 with /172.42.28.1:46118 is aborted: JNLP2-connect: rejected connection for node: temp_slave
Nov 10, 2016 4:46:03 PM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFO: Accepted connection #6 from /172.42.28.1:46120
Nov 10, 2016 4:46:03 PM org.jenkinsci.remoting.engine.JnlpServerHandshake error
WARNING: TCP agent connection handler #6 with /172.42.28.1:46120 is aborted: Unauthorized access
Nov 10, 2016 4:46:04 PM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFO: Accepted connection #7 from /172.42.28.1:46122
Nov 10, 2016 4:46:04 PM hudson.TcpSlaveAgentListener$ConnectionHandler run
WARNING: Connection #7 failed
java.io.EOFException
        at java.io.DataInputStream.readFully(DataInputStream.java:197)
        at java.io.DataInputStream.readFully(DataInputStream.java:169)
        at hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:213)

**Comment by carlossg** [comment]
the slave port is exposed by the jenkins master, so you need to correctly configure it there.
The tunnel option is only to connect somewhere else if your master is behind a firewall, nat,...

**Comment by kopax** [comment]
@carlossg how about if the master is started through marathon ?
I am using HAproxy so the port is still `50000` but this seems to not work. Slave try to connect to dumb port number randomly elected and different from the one used in marathon.

**Comment by carlossg** [comment]
the slave connects through http to jenkins and gets the jnlp port as configured in jenkins security
