### ISSUE TITLE
AccessDeniedException when using workDir

### ISSUE THREAD

**Issue by novaterata** [jenkinsci/docker-jnlp-slave#78]
When I start your docker image with a workDir option, I get an AccessDeniedException.
I don't quite understand which user needs permissions to this directory, and whether this directory is inside the container or on the host system.

**Comment by carlossg** [comment]
user needs permisions and is in the container. For questions use jenkins-users mailing list

**Comment by Arvingrep** [comment]
I get the same issue : 

Nov 22, 2020 6:41:59 AM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: agent.jar
Nov 22, 2020 6:41:59 AM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Nov 22, 2020 6:41:59 AM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 4.6
Exception in thread "main" java.nio.file.AccessDeniedException: /var/jenkins_agent
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.jenkinsci.remoting.engine.WorkDirManager.initializeWorkDir(WorkDirManager.java:211)
	at hudson.remoting.Engine.startEngine(Engine.java:289)
	at hudson.remoting.Engine.startEngine(Engine.java:265)
	at hudson.remoting.jnlp.Main.main(Main.java:283)
	at hudson.remoting.jnlp.Main._main(Main.java:278)
	at hudson.remoting.jnlp.Main.main(Main.java:230)
[root@test03tg jenkins_agent]#  setfacl -m u:jenkins:rwx  /var/jenkins_agent


how  to solve this :user needs permisions and is in the container. For questions use jenkins-users mailing list
